# Generated by Django 3.2.5 on 2021-07-24 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='区域编号')),
                ('name', models.CharField(max_length=30, verbose_name='区域名字')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region')),
            ],
        ),
    ]
